名称：build_Erfan GSIs


#Relation：
#type：[已发布]
#Push：
#分支：
#主
#路径：
#.config‘
#调度：
#-cron：0 8**5
 watch：
类型：[start]n
env：
_rourl：https://bigota.d.miui.com/V12.0.3.0.QEACNXM/miui_MI8_V12.0.3.0.QEACNXM_56da60431d_10.0.zip
 ROM_name：MIUI
 tz：Asia/Shanghai
作业：
构建：
运行-on：Ubuntu-最新的if：github.vent.pository.owner.id==github.vent.sender.id
步骤：
-名称：签出
使用：操作/签出@master
-名称：洁净UP
运行：
 docker RMI`docker映像-q‘
 sudo RM-RF/usr/share/DotNet/etc/etc/php/etc/etc/source.list.d
 sudo-E apt-y-get-y Purge azure-cli ghc*zulu*hhvm llvm*Firefox*DotNet*Powershell OpenJDK*MySQL*php*
 sudo-E sudo-获取更新
 sudo-E sudo-E sudo-EAPT-get-y自动删除-清除
 sudo-E APT-获取清洁

-名称：初始化环境
运行：
 sudo-E sudo-E apt-get-qt更新
 sudo-E apt-get-qq安装git OpenJDK-8-JDK wget
-name：克隆Erfan GSI源代码
运行：git克隆-Recurse-子模块Https://github.com/erfanoabdi/ErfanGSIs.git

-名称：设置Erfan GSI需求
运行：
 sudo chmod-R 777 Erfan GSIs
 cd Erfan GSIs
 sudo bash setup.sh

-名称：DownloadStockRom&GenerateGSI
 Run：Sudo./ErfanGSIs/url2GSI.sh$ROM_ROM$ROM

-名称：zip GSI
 Run：
 mkdir final
 zip zip/home/runner/work/actions_build_ErfanGSIs/actions_build_ErfanGSIs/ErfanGSIs/output/

-名称：将GSI上传到BitSend
 Run：AC.26
 curl-sl https://git.io/file-transfer xSh
./Transfer位Final/GSI.zip
